### ISSUE TITLE
moziloDocuClass deprecated constructor

### ISSUE THREAD

**Issue by drdf** [mozilo/mozilo2.0#18]
> Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; moziloDocuClass has a deprecated constructor in .../mozilo20/docu/docuClass.php on line 6

Gemeldet von User laborix in [mozilo Forum » moziloCMS »  Hier klemmt es! » PHP 7.0.7 - mozilo 2.0 - Doku - Deprecated Error](http://www.mozilo.de/forum/index.php/topic,4204.msg21649.html#msg21649)

**Comment by mozilo** [comment]
gefixt

**Comment by drdf** [comment]
Danke.
