### ISSUE TITLE
Support-Forum wiederholt nicht erreichbar. Datenbankfehler

### ISSUE THREAD

**Issue by drdf** [mozilo/mozilo2.0#21]
Das [mozilo Support-Forum](http://www.mozilo.de/forum/index.php) ist wiederholt nicht erreichbar. Spätestens nach wenigen Klicks kommt die Meldung:

> Datenbankfehler  
> Bitte versuchen Sie es nochmal. Sollte der Fehler wieder auftreten, informieren Sie bitte den Administrator.

**Comment by drdf** [comment]
[mozilo.de](http://www.mozilo.de/) liegt auf [UD Media](https://www.udmedia.de/) Servern - richtig?

**Tipp:** Da gab es Ende April ein MySQL Update auf 5.7 mit neuem *Standard-SQL-Mode*. Mehr dazu findet sich auf https://hilfe.udmedia.de/category/75/umstellung-mysql-57.html

**Comment by marusti** [comment]
Hallo drdf, das Forum läuft seit Mai 2018 wieder.

**Comment by drdf** [comment]
Danke für den Hinweis @marusti.

**Comment by marusti** [comment]
Gerne @drdf . Und Danke für die Antwort auf das eine gemeldete Problem!
